export const salonServices = [
  // ✅ Common Services
  { serviceName: 'Haircut', price: '100' },
  { serviceName: 'Hair Wash', price: '80' },
  { serviceName: 'Hair Coloring', price: '200' },
  { serviceName: 'Hair Spa', price: '150' },
  { serviceName: 'Head Massage', price: '75' },
  { serviceName: 'Facial', price: '100' },
  { serviceName: 'Cleanup', price: '65' },

  // 🧔 Men's Salon Services
  { serviceName: 'Beard Trim', price: '60' },
  { serviceName: 'Beard Styling', price: '80' },
  { serviceName: 'Shaving', price: '50' },
  { serviceName: 'Hair Straightening (Men)', price: '220' },
  { serviceName: 'Hair Smoothening (Men)', price: '240' },
  { serviceName: 'Scalp Treatment', price: '120' },
  { serviceName: 'Men’s Hair Styling', price: '110' },
  { serviceName: 'Men’s Grooming Package', price: '300' },

  // 👩 Women's Salon & Parlour Services
  { serviceName: 'Hair Curling', price: '220' },
  { serviceName: 'Hair Straightening', price: '250' },
  { serviceName: 'Keratin Treatment', price: '280' },
  { serviceName: 'Hair Smoothening', price: '260' },
  { serviceName: 'Body Polishing', price: '160' },
  { serviceName: 'Aromatherapy', price: '190' },
  { serviceName: 'Swedish Massage', price: '170' },
  { serviceName: 'Deep Tissue Massage', price: '200' },
  { serviceName: 'Manicure', price: '60' },
  { serviceName: 'Pedicure', price: '70' },
  { serviceName: 'Nail Extensions', price: '90' },
  { serviceName: 'Nail Art', price: '85' },
  { serviceName: 'Gel Polish Removal', price: '50' },
  { serviceName: 'Party Makeup', price: '130' },
  { serviceName: 'Bridal Makeup', price: '300' },
  { serviceName: 'Eye Makeup', price: '90' },
  { serviceName: 'Saree Draping', price: '110' },
  { serviceName: 'Waxing - Full Body', price: '140' },
  { serviceName: 'Waxing - Underarm', price: '60' },
  { serviceName: 'Waxing - Bikini', price: '80' },
  { serviceName: 'Bleach', price: '55' },
  { serviceName: 'De-tan', price: '95' },
  { serviceName: 'Eyebrow Threading', price: '50' },
  { serviceName: 'Upper Lip Threading', price: '50' },
  { serviceName: 'Ear Piercing', price: '70' },
  { serviceName: 'Mehndi (Henna)', price: '120' },
  { serviceName: 'Tattoo', price: '250' },
  { serviceName: 'Skin Consultation', price: '100' },
  { serviceName: 'Massage', price: '100' }
];
